// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// BUS_A
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of input_val
//        bit 31~0 - input_val[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of output_val
//        bit 31~0 - output_val[31:0] (Read)
// 0x1c : Control signal of output_val
//        bit 0  - output_val_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFIR_BUS_A_ADDR_AP_CTRL         0x00
#define XFIR_BUS_A_ADDR_GIE             0x04
#define XFIR_BUS_A_ADDR_IER             0x08
#define XFIR_BUS_A_ADDR_ISR             0x0c
#define XFIR_BUS_A_ADDR_INPUT_VAL_DATA  0x10
#define XFIR_BUS_A_BITS_INPUT_VAL_DATA  32
#define XFIR_BUS_A_ADDR_OUTPUT_VAL_DATA 0x18
#define XFIR_BUS_A_BITS_OUTPUT_VAL_DATA 32
#define XFIR_BUS_A_ADDR_OUTPUT_VAL_CTRL 0x1c

